### ISSUE TITLE
GCC 6.3.0 Compatibility is Broken

### ISSUE THREAD

**Issue by travisgoodspeed** [boricj/ripem#1]
Howdy y'all,

Rip'em doesn't compile on GCC 6.3.0, which is the default in Debian/Testing.  The cause is the use of const expressions, which are newly illegal as a const isn't really a constant.

```
cc -Wall -Itools/ -o tools/osrom2elf/osrom2elf tools/osrom2elf/osrom2elf.c  -lelf
tools/osrom2elf/osrom2elf.c:32:29: error: initializer element is not constant
 const int OSROM_DATA_SIZE = OSROM_SIZE - OSROM_DATA_OFFSET;
                             ^~~~~~~~~~
tools/osrom2elf/Makefile.in:7: recipe for target 'tools/osrom2elf/osrom2elf' failed
make: *** [tools/osrom2elf/osrom2elf] Error 1
```

You can working around this easily by `CC=clang make clean all`, but GCC compatibility is easy enough to restore with a minor patch.  I'll be sending a pull request that fixes this issue, or you might want to fix it by another method.  Either is cool, and thank you so kindly for starting this project.

73 from Knoxville, Tennessee,
--Travis
